---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Enzo, Layla, Madeleine"
date: "November 16, 2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r load-packages-data, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(tidyr)
library(dplyr)
library(plyr)
library(tidymodels)
library(infer)
library(readr)
library(ggplot2)
library(sf)
library(plotly)
library(tab)
library(pROC)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(kableExtra)
library(gtsummary)
initial_data <- read_csv("../data/500_Cities.csv")
options(scipen=10000)

usa <- map_data('usa')
state <- map_data("state")
```

```{r data-wrangling}
cities <- initial_data %>%
  select(StateAbbr, PlaceName, Population2010, PlaceFIPS, Geolocation, 
         ACCESS2_AdjPrev,CANCER_AdjPrev, CHD_AdjPrev, CHECKUP_AdjPrev,
         COPD_AdjPrev, COLON_SCREEN_AdjPrev,COREM_AdjPrev, COREW_AdjPrev, 
         KIDNEY_AdjPrev, MAMMOUSE_AdjPrev, PAPTEST_AdjPrev) %>%
  dplyr::rename(state = StateAbbr, city = PlaceName, population = Population2010,
         health_access = ACCESS2_AdjPrev, cancer = CANCER_AdjPrev,
         heart_disease = CHD_AdjPrev, checkup = CHECKUP_AdjPrev,
         chronic_lung_disease = COPD_AdjPrev,
         colon_screen = COLON_SCREEN_AdjPrev,
         men_colorectal_cancer_screen = COREM_AdjPrev,
         women_colorectal_cancer_screen = COREW_AdjPrev,
         chronic_kidney_disease = KIDNEY_AdjPrev,
         mammogram = MAMMOUSE_AdjPrev,
         pap_test = PAPTEST_AdjPrev) %>%
  mutate(large_metro = (population >= 1500000), 
         metro = (population >= 500000 & population < 1500000), 
         med_urban = (population >= 200000 & population < 500000), 
         small_urban = (population >= 50000 & population < 200000)) %>%
  mutate(west = (state %in% c("WA", "OR", "ID", "MT", "WY", "CA", "NV", "UT", 
                              "CO", "AZ", "NM")), 
         midwest = (state %in% c("ND", "SD", "NE", "KS", "MN", "IA", "MO", 
                                 "WI", "IL", "IN", "MI", "OH")),
         northeast = (state %in% c("PA", "NY", "VT", "NH", "MA", "CT", "RI", 
                                   "NJ", "ME", "DC")), 
         south = (state %in% c("OK", "TX", "AR", "LA", "MS", "AL", "TN", "KY", 
                               "WV", "VA", "MD", "DE", "NC", "SC", "GA", 
                               "FL"))) %>%
  mutate(region = ifelse(west == TRUE, "West", 
                         ifelse(midwest == TRUE, "Midwest", 
                                ifelse(northeast == TRUE, "Northeast", 
                                       ifelse(south == TRUE,  
                                              "South", NA))))) %>%
  mutate(city_size = ifelse(large_metro == TRUE, "Large Metropolitan", 
                         ifelse(metro == TRUE, "Metropolitan", 
                                ifelse(med_urban == TRUE, "Medium-Size Urban", 
                                       ifelse(small_urban == TRUE, 
                                              "Small-Size Urban", NA))))) %>%
  na.omit(city_size) %>%
  na.omit(region) %>%
  mutate(checkup_n = (population*(checkup/100)), 
         colon_n_screened = (population*(colon_screen/100)), 
         m_colorectal_n_screened = (population*(men_colorectal_cancer_screen/100)),
         w_colorectal_n_screened = 
           (population*(women_colorectal_cancer_screen/100)),
         mammogram_n_screened = (population*(mammogram/100)),
         pap_n_screened = (population*(pap_test/100))) %>%
  mutate(no_checkup_n = (population - checkup_n), 
         no_colon_n_screened = (population - colon_n_screened), 
         no_m_colorectal_n_screened = (population - m_colorectal_n_screened),
         no_w_colorectal_n_screened = 
           (population - w_colorectal_n_screened),
         no_mammogram_n_screened = (population - mammogram_n_screened),
         no_pap_n_screened = (population - pap_n_screened))

# checked the residual plot withouth this and need todo this to make model more accurate
#this is the training data set called model_cities
set.seed(100)

split <- initial_split(cities, prop = 3/4, strata = region)

model_cities <- training(split)
cities_test <- testing(split)

#for introductory visualizations
west_cities <- cities %>%
  filter(west)

midwest_cities <- cities %>%
  filter(midwest)

northeast_cities <- cities %>%
  filter(northeast)

south_cities <- cities %>%
  filter(south)

``` 

# Introductory Visualisations of Data Set

```{r Intro-Visualiszations}

#showing strong correlation between checkup and the other three outcome variables - paptest, colon screen, and mammogram
correlation1 <- cor.test(cities$checkup_n, cities$pap_n_screened,
                         method = "pearson")
correlation2 <- cor.test(cities$checkup_n, cities$colon_n_screened,
                         method = "pearson")
correlation3 <- cor.test(cities$checkup_n, cities$mammogram_n_screened,
                         method = "pearson")
print(correlation1)
print(correlation2)
print(correlation3)

#wrangling for visualizations
cities2 <- cities %>%
  filter( region != "NA") %>%
  mutate(logcheckup_n = log(checkup_n))

#(1) boxplots of checkup (n and log) by region
ggplot(data = cities2,
       aes(x = region, y = logcheckup_n,
           color = region)) +
  geom_boxplot()

#(2) histograms showing mean checkup (not that well), faceted by region
cities2 %>%
ggplot(aes(x = logcheckup_n)) +
  facet_wrap(~region) +
  geom_histogram()

#(3) anova shows means of checkup (n and log) are different among the regions
anova1 <- aov(logcheckup_n ~ region, data = cities2)
tidy(anova1)

#(4) boxplots of checkup (n and log) by city size
ggplot(data = cities2,
       aes(x = city_size, y = logcheckup_n,
           color = city_size)) +
  geom_boxplot()

#(5) histograms showing mean checkup, faceted by city size
cities2 %>%
ggplot(aes(x = logcheckup_n)) +
  facet_wrap(~city_size) +
  geom_histogram()

#(6) anova shows means of checkup (n and log) are different among the city sizes
anova2 <- aov(logcheckup_n ~ city_size, data = cities2)
tidy(anova2)

#(7) enzo's graph for health access vs checkup
ggplot(data = cities2,
       aes(x = health_access, y = logcheckup_n)) +
  geom_col(aes(width = 1))

#madeleine's graph for health access vs checkup
ggplot(cities, aes(x = health_access,
                   y= checkup))+
  geom_point()

```

```{r Simple-Marginal-Relationship1, warning=FALSE, message=FALSE, echo=FALSE} 
 cities1 <- cities %>%
   na.omit(city_size)

ggplot(cities1, aes(x = city_size, 
                   y = checkup_n))+ 
  geom_bar( stat = 'identity')+ 
  labs( x = "City Size", 
        y = "Checkups per Capita",
        title = "Prevalence of Checkups by City Size") +
  theme(axis.text.x = element_text(angle = 45,hjust=1))+ 
  theme(legend.position = "none")
```

```{r introvis-checkup6-region}
cities2 <- cities %>%
  filter( region != "NA")

ggplot(cities2, aes(x = region, 
                    y = checkup, 
                    fill = region))+
  geom_bar( stat = 'identity' )+ 
  labs( x = "Region", 
        y = "Prevalence of checkup",
        title = "Prevalence of checkups by Region") +
  theme(axis.text.x = element_text(angle = 45,hjust=1))+
  theme(legend.position = "none")
```


```{r introvis-checkup8-lackHC}
ggplot(cities, aes(x = health_access,
                   y= checkup,
                   color = city_size))+
  geom_point()+ 
  labs( x = "Lack of Health Care Access", 
        y = "Checkups Count",
        title = "Prevalence of Checkups and Lack of Healthcare Access")
#cloud of points means something-- don't forget this later on 
#gross 
```

# Models

```{r Multiple-Logistic-Regression-Model, warning=FALSE, message=FALSE, echo=FALSE}

checkup_fit <- glm(cbind(checkup_n, no_checkup_n) ~ region + 
                     city_size + health_access, 
                   family = binomial, data = model_cities)

checkup_fit_df1 <- tidy(checkup_fit, exponentiate = TRUE, intercept = TRUE)
checkup_fit_df1_f <- checkup_fit_df1[, -c(3, 4)]
kable(checkup_fit_df1_f)

#interaction model
checkup_fit2 <- glm(cbind(checkup_n, no_checkup_n) ~ region +
                     city_size + health_access + region*city_size +
                      region*health_access + city_size*health_access,
                   family = binomial, data = model_cities)

checkup_fit_df2 <- tidy(checkup_fit2, exponentiate = TRUE, intercept = TRUE)
checkup_fit_df2_f <- checkup_fit_df2[, -c(3, 4)]
kable(checkup_fit_df2_f)
```

# Model Validation

```{r model-validation}
# predictions from no interaction model 

test_prob1 = predict(checkup_fit, newdata = cities_test, type = "response")

cities_test1 <-
  merge(cities_test, test_prob1, by = "row.names", all.x = TRUE)

# prediction from model with interaction

test_prob2 = predict(checkup_fit2, newdata = cities_test, type = "response")

cities_test2 <-
  merge(cities_test, test_prob2, by = "row.names", all.x = TRUE)

#rmse against model/training data set

test_prob_model = predict(checkup_fit, newdata = model_cities, type = "response")
model_cities1 <- merge(model_cities, test_prob_model, by = "row.names", all.x = TRUE)
rmse(model_cities1, truth = (checkup/100), estimate = test_prob_model)

test_prob_model2 = predict(checkup_fit2, newdata = model_cities, type = "response")
model_cities2 <- merge(model_cities, test_prob_model2, by = "row.names", all.x = TRUE)
rmse(model_cities2, truth = (checkup/100), estimate = test_prob_model)

#calculate root mean standard error of both models against test data set

rmse1 <- rmse(cities_test1, truth = (checkup/100), estimate = test_prob1)
rmse2 <- rmse(cities_test2, truth = (checkup/100), estimate = test_prob2)

rmse1 %>%
  kable()

rmse2 %>%
  kable()

```